// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJgJUg9Rpd1cbzbb6AjYPGUoWyg-kCbM4',
    appId: '1:438160748395:web:39ef12edad76b320ffe62e',
    messagingSenderId: '438160748395',
    projectId: 'hem-routine-app-dev',
    authDomain: 'hem-routine-app-dev.firebaseapp.com',
    storageBucket: 'hem-routine-app-dev.appspot.com',
    measurementId: 'G-YCNT1FJPTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDENMWOD6788FUMTfm2w0J2kqs1iaIeyX4',
    appId: '1:438160748395:android:5139bc927cef6b81ffe62e',
    messagingSenderId: '438160748395',
    projectId: 'hem-routine-app-dev',
    storageBucket: 'hem-routine-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnOvTlNd0b-7KG_QQ6qVShH_5DKAfmrxM',
    appId: '1:438160748395:ios:de37f99a46739964ffe62e',
    messagingSenderId: '438160748395',
    projectId: 'hem-routine-app-dev',
    storageBucket: 'hem-routine-app-dev.appspot.com',
    iosClientId: '438160748395-cligtbqnt6tc3ltgpeolc0p8a44g9ggk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudToyProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnOvTlNd0b-7KG_QQ6qVShH_5DKAfmrxM',
    appId: '1:438160748395:ios:de37f99a46739964ffe62e',
    messagingSenderId: '438160748395',
    projectId: 'hem-routine-app-dev',
    storageBucket: 'hem-routine-app-dev.appspot.com',
    iosClientId: '438160748395-cligtbqnt6tc3ltgpeolc0p8a44g9ggk.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudToyProj',
  );
}
