// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSh4VvApQ-F1Eu_m4_FqsD2NMPx6rTR6E',
    appId: '1:841692023522:web:f674d2945be71ad7d0ecbb',
    messagingSenderId: '841692023522',
    projectId: 'hem-routine-app',
    authDomain: 'hem-routine-app.firebaseapp.com',
    storageBucket: 'hem-routine-app.appspot.com',
    measurementId: 'G-CR17YMQNY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBWxQGC8Q5TTDhlcO7sy1MlExIxXat0UA',
    appId: '1:841692023522:android:cae4dda17c2adf8ad0ecbb',
    messagingSenderId: '841692023522',
    projectId: 'hem-routine-app',
    storageBucket: 'hem-routine-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ1zgVlzvOIaauLSSPUpoTZDM9Y6yJQfQ',
    appId: '1:841692023522:ios:1c5dfdf32d6b12eed0ecbb',
    messagingSenderId: '841692023522',
    projectId: 'hem-routine-app',
    storageBucket: 'hem-routine-app.appspot.com',
    iosClientId: '841692023522-vi5cbtarckl3h4k7sjcaj674afftmggh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudToyProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ1zgVlzvOIaauLSSPUpoTZDM9Y6yJQfQ',
    appId: '1:841692023522:ios:1c5dfdf32d6b12eed0ecbb',
    messagingSenderId: '841692023522',
    projectId: 'hem-routine-app',
    storageBucket: 'hem-routine-app.appspot.com',
    iosClientId: '841692023522-vi5cbtarckl3h4k7sjcaj674afftmggh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudToyProj',
  );
}
